# ============================================
# Thermostate Basis
# EnthÃ¤lt: externe Component, globale Schalter und Master-Sensorik
# 
# Die eigentlichen Thermostat-Instanzen werden direkt im jeweiligen
# Setup unter packages: als !include thermostat_template.yaml eingebunden.
# ============================================

external_components:
  - source:
      type: git
      url: https://github.com/kwittwer/esphome_kfw_lib
      ref: main
      path: B16M/platform/components
    components: [dummy_thermostat]

# ============================================
# Global Switches (fÃ¼r alle Thermostaten)
# ============================================

switch:
  - platform: template
    name: "Lokale Heizregelung"
    id: local_control_switch
    entity_category: config
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    
  - platform: template
    name: "Heizung Hauptschalter"
    id: heating_master_switch
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: config
    optimistic: true

# ============================================
# Global Binary Sensor (fÃ¼r Heizung Master-Switch)
# ============================================

binary_sensor:
  - platform: template
    name: "Heizung Hauptschalter"
    id: hw_master_sw
    entity_category: diagnostic
    lambda: |-
      if (id(DI1).state == true) {
        return true;
      } else {
        return false;
      }
