esphome:
  name: modbus-tcp-rtu-bridge
  friendly_name: Modbus TCP to RTU Bridge

esp32:
  variant: esp32
  framework:
    type: esp-idf

web_server:
  port: 80
  version: 3

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  fast_connect: true

logger:
  level: DEBUG

api:

ota:
  - platform: esphome

switch:
  - platform: gpio
    name: "a2-light1"
    pin: 15
    inverted: false
  - platform: gpio
    name: "a2-light2"
    pin: 2
    inverted: false

binary_sensor:
  - platform: gpio
    name: "a2-input1"
    pin:
      number: 36
      inverted: true
  - platform: gpio
    name: "a2-input2"
    pin:
      number: 39
      inverted: true

uart:
  - id: uart_bus
    tx_pin: GPIO32
    rx_pin: GPIO35
    baud_rate: 9600
    data_bits: 8
    parity: NONE
    stop_bits: 1

external_components:
  - source:
      type: git
      url: https://github.com/rosenrot00/esphome_modbus_bridge
    components: [modbus_bridge]
    refresh: 0s

modbus_bridge:
  id: mb_bridge
  uart_id: uart_bus