esphome:
  name: minimal-test-c3

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

logger:

api:

ota:
  platform: esphome

wifi:
  ssid: "test-ssid"
  password: "test-password"

captive_portal:
